#!/usr/bin/env node
/**
 * One command to run everything for a demo, in any shell (PowerShell, cmd, Git Bash).
 *
 *   node scripts/demo.mjs check             pre-flight: is everything ready? (also runs inside `up`)
 *   node scripts/demo.mjs up                start media server + scheduler + worker(s), watch them
 *   node scripts/demo.mjs status            is analysis actually flowing? (queue, cameras, recent logs)
 *   node scripts/demo.mjs analysis-off      un-flag every camera for server analysis (--yes to apply)
 *   node scripts/demo.mjs stop              kill leftovers on the demo ports (add --anpr to include the plate reader)
 *   node scripts/demo.mjs anpr-setup        one time: install the plate-reader (ANPR) service on this PC
 *   node scripts/demo.mjs anpr-test         measure the plate reader on a real frame (speed, key, device)
 *
 * `up` options:  --workers N (default 1)   --dev (tsx + Vite instead of the production build)
 *                --build (force a rebuild)  --single (one process, in-memory queue, no Redis)
 *                --anpr (also run the plate reader on this PC)   --tunnel (anpr + public address for the deployed app)
 *                --no-media   --no-pg   --all-logs (show every analysis in the Logs tab, not only notable ones)
 *
 * Settings come from scale.local (and demo.local if present). Both are git-ignored. See DEMO.md.
 */
import fs from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import { spawn, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';

// pg prints a long SSL-mode notice on every connect; it is noise for this tool.
const emitWarning = process.emitWarning;
process.emitWarning = (w, ...rest) => (/SSL modes/.test(String(w)) ? undefined : emitWarning.call(process, w, ...rest));

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const argv = process.argv.slice(2);
const command = argv.find((a) => !a.startsWith('--')) || 'help';
const flag = (f) => argv.includes(f);
const opt = (f, d) => { const i = argv.indexOf(f); return i >= 0 && argv[i + 1] ? argv[i + 1] : d; };
const WIN = process.platform === 'win32';

const APP_PORT = 3000, MEDIA_PORT = 8888;
const WORKERS = Math.max(0, Number(opt('--workers', 1)));
const GRID_HOST = '103.250.160.189';
const ANPR_PORT = 8000;
const ANPR_DIR = path.join(ROOT, 'anpr-service');
const VENV_PY = path.join(ANPR_DIR, '.venv', WIN ? 'Scripts' : 'bin', WIN ? 'python.exe' : 'python');

// ---------------------------------------------------------------- output helpers
const C = { reset: '\x1b[0m', dim: '\x1b[2m', red: '\x1b[31m', green: '\x1b[32m', yellow: '\x1b[33m', cyan: '\x1b[36m', magenta: '\x1b[35m', blue: '\x1b[34m' };
const paint = (c, s) => (process.stdout.isTTY ? C[c] + s + C.reset : s);
const PASS = paint('green', 'PASS'), WARN = paint('yellow', 'WARN'), FAIL = paint('red', 'FAIL'), INFO = paint('cyan', 'INFO');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const mask = (s) => String(s).replace(/(:\/\/[^:@/]*:)[^@]*@/g, '$1***@');

// ---------------------------------------------------------------- config
function parseEnvFile(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const raw of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 1) continue;
    let v = line.slice(eq + 1).trim();
    if (v.length >= 2 && ((v.startsWith("'") && v.endsWith("'")) || (v.startsWith('"') && v.endsWith('"')))) v = v.slice(1, -1);
    out[line.slice(0, eq).trim()] = v;
  }
  return out;
}

/** The shared ANPR password is invented, not issued by anyone. Make one once and keep it in scale.local. */
function ensureAnprKey() {
  const file = path.join(ROOT, 'scale.local');
  const existing = parseEnvFile(file).ANPR_API_KEY || process.env.ANPR_API_KEY;
  if (existing) return existing;
  const key = randomBytes(32).toString('hex'); // letters and digits only, as the service requires
  fs.appendFileSync(file, `\n# Shared secret between the app and the ANPR service (generated by scripts/demo.mjs).\nANPR_API_KEY=${key}\n`);
  console.log(`${INFO}  generated ANPR_API_KEY and saved it to scale.local`);
  return key;
}

function findPython() {
  const tries = WIN ? [['py', ['-3']], ['python', []]] : [['python3', []], ['python', []]];
  for (const [cmd, pre] of tries) {
    const r = spawnSync(cmd, [...pre, '--version'], { encoding: 'utf8' });
    const m = r.status === 0 && /Python (3\.\d+)\.(\d+)/.exec(`${r.stdout}${r.stderr}`); // the Microsoft Store stub exits non-zero
    if (m) return { cmd, pre, version: m[1] + '.' + m[2] };
  }
  return null;
}
function findCloudflared() {
  for (const p of ['C:\\Program Files (x86)\\cloudflared\\cloudflared.exe', 'C:\\Program Files\\cloudflared\\cloudflared.exe']) if (fs.existsSync(p)) return p;
  const r = spawnSync(WIN ? 'where' : 'which', ['cloudflared'], { encoding: 'utf8' });
  return r.status === 0 ? r.stdout.split(/\r?\n/)[0] : null;
}
const anprInstalled = () => fs.existsSync(VENV_PY) && spawnSync(VENV_PY, ['-c', 'import fast_alpr, fastapi, uvicorn'], { stdio: 'ignore' }).status === 0;

function loadConfig() {
  const env = { ...process.env, ...parseEnvFile(path.join(ROOT, 'demo.local')), ...parseEnvFile(path.join(ROOT, 'scale.local')) };
  env.GRID_EMAIL ||= env.STREAM_EMAIL;
  env.GRID_PASSWORD ||= env.STREAM_PASSWORD;
  env.STREAM_EMAIL ||= env.GRID_EMAIL;
  env.STREAM_PASSWORD ||= env.GRID_PASSWORD;
  env.MEDIA_VIEWER_PASSWORD ||= 'localdemo2026';
  env.REGISTRY_API_KEY ||= 'test123';
  env.SERVER_ANALYSIS ||= 'true';
  if (flag('--no-pg')) for (const k of ['EVENT_STORE', 'DATABASE_URL', 'DATABASE_SSL', 'FIRESTORE_LOG_MODE']) delete env[k];
  if (flag('--single')) { delete env.REDIS_URL; delete env.ANALYSIS_ROLE; }
  // The Logs tab reads Firestore; by default only notable events are mirrored there once Postgres is the record.
  if (flag('--all-logs')) env.FIRESTORE_LOG_MODE = 'all';
  // --anpr: the plate-reading service runs on this PC, so the app reaches it on localhost (no tunnel needed).
  if (flag('--anpr') || flag('--tunnel')) {
    env.ANPR_SERVICE_URL = `http://127.0.0.1:${ANPR_PORT}`;
  }
  return env;
}

// ---------------------------------------------------------------- small probes
const tcp = (host, port, ms = 5000) => new Promise((resolve) => {
  const s = net.connect({ host, port });
  const done = (ok) => { s.destroy(); resolve(ok); };
  s.setTimeout(ms, () => done(false)); s.once('connect', () => done(true)); s.once('error', () => done(false));
});
// Binding 0.0.0.0 succeeds on Windows even when another program listens on 127.0.0.1:port, so connect first.
const portFree = async (port) => !(await tcp('127.0.0.1', port, 1000)) && (await portBindable(port));
const portBindable = (port) => new Promise((resolve) => {
  const s = net.createServer();
  s.once('error', () => resolve(false));
  s.once('listening', () => s.close(() => resolve(true)));
  s.listen(port, '0.0.0.0');
});
async function getJson(url, headers = {}, ms = 8000) {
  const r = await fetch(url, { headers, signal: AbortSignal.timeout(ms) });
  if (!r.ok) throw new Error('HTTP ' + r.status);
  return r.json();
}
function findBash() {
  for (const p of ['C:\\Program Files\\Git\\bin\\bash.exe', 'C:\\Program Files (x86)\\Git\\bin\\bash.exe', '/bin/bash', '/usr/bin/bash']) if (fs.existsSync(p)) return p;
  const r = spawnSync(WIN ? 'where' : 'which', ['bash'], { encoding: 'utf8' });
  const hit = r.status === 0 ? r.stdout.split(/\r?\n/).find((l) => l && !/system32/i.test(l)) : null; // System32\bash.exe is WSL, not Git Bash
  return hit || null;
}
function newestMtime(p) {
  let newest = 0;
  const walk = (d) => { for (const e of fs.readdirSync(d, { withFileTypes: true })) { const f = path.join(d, e.name); if (e.isDirectory()) walk(f); else newest = Math.max(newest, fs.statSync(f).mtimeMs); } };
  fs.statSync(p).isDirectory() ? walk(p) : (newest = fs.statSync(p).mtimeMs);
  return newest;
}
const distStale = () => {
  const dist = path.join(ROOT, 'dist', 'server.cjs');
  if (!fs.existsSync(dist) || !fs.existsSync(path.join(ROOT, 'dist', 'index.html'))) return true;
  const built = fs.statSync(dist).mtimeMs;
  return ['server.ts', 'server', 'src', 'index.html', 'package.json'].some((p) => fs.existsSync(path.join(ROOT, p)) && newestMtime(path.join(ROOT, p)) > built + 1000);
};

// ---------------------------------------------------------------- check
async function check(cfg, { quiet = false } = {}) {
  const rows = [];
  const add = (level, what, detail = '') => rows.push({ level, what, detail });
  const wantRedis = !flag('--single');
  const wantPg = cfg.EVENT_STORE === 'postgres';

  const major = Number(process.versions.node.split('.')[0]);
  add(major >= 20 ? PASS : FAIL, 'Node.js', `v${process.versions.node}${major >= 20 ? '' : ' (need 20+)'}`);

  const ff = spawnSync('ffmpeg', ['-version'], { encoding: 'utf8' });
  add(ff.status === 0 ? PASS : FAIL, 'ffmpeg', ff.status === 0 ? ff.stdout.split('\n')[0].slice(0, 40) : 'not found on PATH - frame capture will fail');

  const missing = ['FIREBASE_SERVICE_ACCOUNT', 'GEMINI_API_KEY', 'STREAM_EMAIL', 'STREAM_PASSWORD'].filter((k) => !cfg[k]);
  add(missing.length ? FAIL : PASS, 'scale.local values', missing.length ? 'missing: ' + missing.join(', ') : 'all required values set');
  try { const j = JSON.parse(cfg.FIREBASE_SERVICE_ACCOUNT || ''); add(j.private_key && j.client_email ? PASS : FAIL, 'Firebase service account', 'project ' + j.project_id); }
  catch { add(FAIL, 'Firebase service account', 'FIREBASE_SERVICE_ACCOUNT is not valid JSON (one line, in single quotes)'); }

  if (wantRedis) {
    if (!cfg.REDIS_URL) add(FAIL, 'Redis', 'REDIS_URL not set (use --single to run without Redis)');
    else {
      try {
        const { default: Redis } = await import('ioredis');
        const u = new URL(cfg.REDIS_URL);
        const r = new Redis({ host: u.hostname, port: Number(u.port) || 6379, username: u.username || undefined, password: decodeURIComponent(u.password) || undefined, ...(u.protocol === 'rediss:' ? { tls: {} } : {}), connectTimeout: 10000, maxRetriesPerRequest: 1, lazyConnect: true, retryStrategy: () => null });
        r.on('error', () => {});
        const t0 = Date.now(); await r.connect(); await r.ping(); const ms = Date.now() - t0; r.disconnect();
        add(PASS, 'Redis', `${u.hostname}  (${ms} ms)`);
      } catch (e) { add(FAIL, 'Redis', mask(String(e.message)).slice(0, 90)); }
    }
  } else add(INFO, 'Redis', 'skipped (--single: in-memory queue)');

  if (wantPg) {
    try {
      const { default: pg } = await import('pg');
      const pool = new pg.Pool({ connectionString: cfg.DATABASE_URL, connectionTimeoutMillis: 20000 });
      const t0 = Date.now(); await pool.query('select 1'); await pool.end();
      add(PASS, 'Postgres', `reachable and warm (${Date.now() - t0} ms)`);
    } catch (e) { add(FAIL, 'Postgres', mask(String(e.message)).slice(0, 90)); }
  } else add(INFO, 'Postgres', 'not used (events go to Firestore)');

  const [rtsp, whep] = await Promise.all([tcp(GRID_HOST, 8554), tcp(GRID_HOST, 8889)]);
  add(rtsp ? PASS : WARN, 'Camera grid RTSP :8554', rtsp ? 'reachable' : 'unreachable (third-party server; analysis and media will fail until it is back)');
  add(whep ? PASS : WARN, 'Camera grid WebRTC :8889', whep ? 'reachable' : 'unreachable');

  const ports = [APP_PORT, ...Array.from({ length: WORKERS }, (_, i) => APP_PORT + 1 + i), ...(flag('--no-media') ? [] : [MEDIA_PORT])];
  const busy = [];
  for (const p of ports) if (!(await portFree(p))) busy.push(p);
  add(busy.length ? FAIL : PASS, 'Ports', busy.length ? `in use: ${busy.join(', ')} - run: node scripts/demo.mjs stop` : `free: ${ports.join(', ')}`);

  if (!flag('--no-media')) {
    const bash = findBash();
    add(bash ? PASS : FAIL, 'Git Bash (for the media server)', bash || 'not found - install Git for Windows, or use --no-media');
    const bin = path.join(ROOT, 'media-server', 'bin', WIN ? 'mediamtx.exe' : 'mediamtx');
    add(fs.existsSync(bin) ? PASS : WARN, 'MediaMTX binary', fs.existsSync(bin) ? 'present' : 'will be downloaded on first start (needs internet)');
  }

  if (!flag('--dev')) add(distStale() ? INFO : PASS, 'Production build', distStale() ? 'out of date - `up` will rebuild (about a minute)' : 'up to date');

  if (flag('--anpr') || flag('--tunnel')) {
    const base = `http://127.0.0.1:${ANPR_PORT}`;
    if (!(await portFree(ANPR_PORT))) {
      // Something is already on the port. If it is an ANPR service that accepts our key, just use it.
      try {
        const h = await getJson(base + '/healthz', {}, 5000);
        const probe = await fetch(base + '/v1/anpr', { method: 'POST', headers: { 'X-ANPR-Key': cfg.ANPR_API_KEY || '', 'Content-Type': 'application/octet-stream' }, body: new Uint8Array(0), signal: AbortSignal.timeout(8000) });
        if (probe.status === 401) add(FAIL, 'ANPR service (already running)', `rejects our key. Put the key it was started with into scale.local as ANPR_API_KEY=..., or stop it: node scripts/demo.mjs stop --anpr`);
        else add(PASS, 'ANPR service (already running)', `will be reused: ${h.status || 'ok'}, device ${h.device || '?'}${h.auth_required ? ', key accepted' : ''}`);
      } catch { add(FAIL, `Port ${ANPR_PORT} (ANPR)`, 'in use by something that is not an ANPR service - free it or stop it: node scripts/demo.mjs stop --anpr'); }
    } else {
      // We will start it: needs Python and the installed packages.
      const py = findPython();
      add(py ? PASS : FAIL, 'Python (for ANPR)', py ? `${py.cmd} ${py.version}` : 'not found - install Python 3.10-3.12 from python.org, or drop --anpr');
      add(anprInstalled() ? PASS : FAIL, 'ANPR packages', anprInstalled() ? 'installed (anpr-service/.venv)' : 'not installed - run once: node scripts/demo.mjs anpr-setup');
    }
    if (flag('--tunnel')) { const cf = findCloudflared(); add(cf ? PASS : FAIL, 'cloudflared (tunnel)', cf || 'not found - install it, or drop --tunnel'); }
  } else if (cfg.ANPR_SERVICE_URL) {
    // A service somewhere else (GPU box behind a tunnel): test it, including the key, like production would.
    const base = cfg.ANPR_SERVICE_URL.replace(/\/+$/, '');
    try {
      const h = await getJson(base + '/healthz', {}, 8000);
      const probe = await fetch(base + '/v1/anpr', { method: 'POST', headers: { 'X-ANPR-Key': cfg.ANPR_API_KEY || '', 'Content-Type': 'application/octet-stream' }, body: new Uint8Array(0), signal: AbortSignal.timeout(8000) });
      const keyBad = probe.status === 401;
      add(keyBad ? FAIL : PASS, 'ANPR service', keyBad ? `${base} rejected ANPR_API_KEY (401) - it must match the service's key` : `${h.status || 'ok'}, device ${h.device || '?'}, key accepted`);
    } catch (e) { add(WARN, 'ANPR service', `${base} not answering (${e.message}) - plates fall back to Gemini`); }
  } else add(INFO, 'ANPR service', 'off - plates are read by Gemini ("unverified read"). Use --anpr to run the plate reader on this PC');

  if (!quiet) {
    console.log(paint('cyan', '\nPre-flight check'));
    for (const r of rows) console.log(`  ${r.level}  ${r.what.padEnd(34)} ${paint('dim', r.detail)}`);
  }
  const fails = rows.filter((r) => r.level === FAIL).length;
  if (!quiet) console.log(fails ? paint('red', `\n${fails} problem(s) to fix before starting.\n`) : paint('green', '\nReady.\n'));
  return fails;
}

// ---------------------------------------------------------------- processes
const children = [];
const seenOnce = new Set();
function launch(label, color, cmd, args, env, opts = {}) {
  const child = spawn(cmd, args, { cwd: opts.cwd || ROOT, env, stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true });
  fs.mkdirSync(path.join(ROOT, '.demo-logs'), { recursive: true });
  const log = fs.createWriteStream(path.join(ROOT, '.demo-logs', `${label}.log`), { flags: 'w' });
  const tag = paint(color, `[${label}]`.padEnd(10));
  const pump = (stream) => {
    let buf = '';
    stream.on('data', (d) => {
      log.write(d);
      buf += d.toString();
      let i;
      while ((i = buf.indexOf('\n')) >= 0) {
        const line = buf.slice(0, i).replace(/\r$/, ''); buf = buf.slice(i + 1);
        if (!line.trim()) continue;
        if (/Eviction policy is/.test(line)) { if (seenOnce.has('evict')) continue; seenOnce.add('evict'); }
        opts.onLine?.(line);
        if (NOISE.test(line) || (opts.hide && opts.hide.test(line))) continue;
        console.log(`${tag} ${line}`);
      }
    });
  };
  pump(child.stdout); pump(child.stderr);
  child.on('exit', (code) => { if (!shuttingDown) console.log(`${tag} ${paint('red', `exited with code ${code}`)} (see .demo-logs/${label}.log)`); });
  children.push({ label, child });
  return child;
}
// Library notices that repeat on every start and mean nothing for a demo.
const NOISE = /SSL modes|next major version|To prepare for this change|sslmode=verify-full|uselibpqcompat|libpq-ssl|trace-warnings|CJS build of Vite/;
let shuttingDown = false;
function killTree(pid) {
  if (WIN) spawnSync('taskkill', ['/PID', String(pid), '/T', '/F'], { stdio: 'ignore' });
  else { try { process.kill(-pid); } catch { try { process.kill(pid); } catch { /* gone */ } } }
}
function shutdown() {
  if (shuttingDown) return;
  shuttingDown = true;
  console.log(paint('yellow', '\nStopping everything...'));
  for (const { child } of children) if (child.pid) killTree(child.pid);
  setTimeout(() => process.exit(0), 1500);
}

async function waitFor(what, fn, timeoutMs) {
  const t0 = Date.now();
  let lastErr = '';
  while (Date.now() - t0 < timeoutMs) {
    try { if (await fn()) return true; } catch (e) { lastErr = e.message; }
    await sleep(1500);
  }
  console.log(`${FAIL}  ${what} did not come up within ${Math.round(timeoutMs / 1000)}s ${lastErr}`);
  return false;
}

// ---------------------------------------------------------------- up
async function up() {
  const cfg = loadConfig();
  // Always replace a previous run: stop whatever still holds the demo ports (pass --keep to skip).
  if (!flag('--keep') && stop({ quiet: true })) {
    for (let i = 0; i < 20 && !(await portFree(MEDIA_PORT) && await portFree(APP_PORT)); i++) await new Promise((r) => setTimeout(r, 500));
  }
  if (await check(cfg)) process.exit(1);

  const dev = flag('--dev');
  if (!dev && (flag('--build') || distStale())) {
    console.log(paint('cyan', 'Building the app (about a minute)...'));
    const b = spawnSync(WIN ? 'npm.cmd run build' : 'npm run build', { cwd: ROOT, stdio: 'inherit', shell: true });
    if (b.status !== 0) { console.log(`${FAIL}  build failed`); process.exit(1); }
  }
  const entry = dev ? [path.join(ROOT, 'node_modules', 'tsx', 'dist', 'cli.mjs'), 'server.ts'] : [path.join(ROOT, 'dist', 'server.cjs')];
  const single = flag('--single');
  const base = { ...cfg, NODE_ENV: dev ? 'development' : 'production' };

  // 1. media server (MediaMTX), via the existing script in its media-only mode
  if (!flag('--no-media')) {
    const bash = findBash();
    // Grid cameras MediaMTX cannot package play only after a Quick Sync re-encode to H.264: the H.265 ones, and
    // cam09 13 14 24 27 28 (H.264 with B-frames: MediaMTX's HLS muxer dies with "too many reordered frames") and cam30
    // (a keyframe only about once a minute, so HLS segments grow to 59 s) are re-encoded too; seen in the browser on 2026-10-08.
    // cam22 sends no usable frames, so it is left out. Set MEDIA_TRANSCODE_IDS= (empty) in scale.local on a PC
    // without Intel Quick Sync to switch it off.
    // Better than any hard-coded list: when `node --import tsx scripts/media-config.ts write` has produced a paths file from the
    // camera profiles, the media server starts from that (each camera gets the recipe its probe measured). MEDIA_TRANSCODE_IDS in
    // scale.local, set on purpose, still wins. The list below is the fallback until a probe has been run.
    const generated = path.join(ROOT, 'media-server', 'bin', 'paths.generated.yml');
    const useGenerated = fs.existsSync(generated) && !('MEDIA_TRANSCODE_IDS' in base);
    const transcode = useGenerated ? '' : 'MEDIA_TRANSCODE_IDS' in base ? base.MEDIA_TRANSCODE_IDS : 'cam06,cam12,cam17,cam26,cam09:h264,cam13:h264,cam14:h264,cam24:h264,cam27:h264,cam28:h264,cam30:h264';
    console.log(`${INFO}  media paths: ${useGenerated ? `generated from camera profiles (${path.relative(ROOT, generated)})` : transcode ? 'the built-in re-encode list (run scripts/media-config.ts write to generate one from the profiles)' : 'no re-encoding'}`);
    launch('media', 'blue', bash, ['scripts/local-demo.sh'], { ...base, MEDIA_ONLY: '1', PORT: String(APP_PORT), MEDIA_HLS_PORT: String(MEDIA_PORT), MEDIA_TRANSCODE_IDS: transcode, MEDIA_PATHS_FILE: useGenerated ? generated : '' }, { hide: /^\s*$/ });
    const ok = await waitFor('media server', async () => (await fetch(`http://127.0.0.1:${MEDIA_PORT}/cam01/index.m3u8?cookieCheck=1`, { signal: AbortSignal.timeout(4000) })).status === 401, 60_000);
    if (!ok) { shutdown(); return; }
    console.log(`${PASS}  media server up on :${MEDIA_PORT}`);
  }

  // ANPR plate reader on this PC. The first start downloads the model weights, so allow several minutes.
  if ((flag('--anpr') || flag('--tunnel')) && !(await portFree(ANPR_PORT))) {
    console.log(`${INFO}  reusing the ANPR service already running on :${ANPR_PORT}`);
  } else if (flag('--anpr') || flag('--tunnel')) {
    base.ANPR_API_KEY ||= ensureAnprKey();
    launch('anpr', 'yellow', VENV_PY, ['-m', 'uvicorn', 'anpr_service.main:app', '--host', '127.0.0.1', '--port', String(ANPR_PORT)],
      { ...base, ANPR_DEVICE: base.ANPR_DEVICE || 'auto' }, { cwd: ANPR_DIR });
    console.log(paint('dim', '  starting ANPR (first run downloads the plate models; this can take a few minutes)...'));
    const ok = await waitFor('ANPR service', async () => (await getJson(`http://127.0.0.1:${ANPR_PORT}/healthz`, {}, 4000)).status !== undefined, 600_000);
    if (!ok) { shutdown(); return; }
    console.log(`${PASS}  ANPR service up on :${ANPR_PORT}`);
  }
  if (flag('--tunnel')) {
    let url = null;
    launch('tunnel', 'dim', findCloudflared(), ['tunnel', '--url', `http://localhost:${ANPR_PORT}`], base, {
      onLine: (line) => { const m = !url && line.match(/https:\/\/[a-z0-9-]+\.trycloudflare\.com/); if (m) { url = m[0]; } },
    });
    await waitFor('Cloudflare tunnel', async () => url !== null, 60_000);
    if (url) {
      console.log(paint('yellow', `\n  Tunnel for the DEPLOYED app:  ANPR_SERVICE_URL = ${url}`));
      console.log(paint('yellow', `                                ANPR_API_KEY     = (the value in scale.local)\n  Set both on Render and redeploy. The address changes every time this runs.\n`));
    }
  }

  // 2. scheduler (also serves the web app), 3. workers
  const schedEnv = { ...base, PORT: String(APP_PORT), ...(single ? {} : { ANALYSIS_ROLE: 'scheduler' }),
    ...(flag('--no-media') ? {} : { MEDIA_SERVER_URL: `http://localhost:${MEDIA_PORT}`, MEDIA_ALLOW_GUESTS: 'true', MEDIA_MAX_LIVE_TILES: base.MEDIA_MAX_LIVE_TILES || '6' }) };
  launch(single ? 'app' : 'scheduler', 'green', process.execPath, entry, schedEnv);
  if (!single) for (let i = 0; i < WORKERS; i++) {
    launch(`worker${i + 1}`, 'magenta', process.execPath, entry, { ...base, PORT: String(APP_PORT + 1 + i), ANALYSIS_ROLE: 'worker' });
  }

  const key = { 'X-Registry-Api-Key': cfg.REGISTRY_API_KEY };
  const statusOf = (port) => getJson(`http://localhost:${port}/api/analysis/status`, key);
  const ports = single ? [APP_PORT] : [APP_PORT, ...Array.from({ length: WORKERS }, (_, i) => APP_PORT + 1 + i)];
  for (const p of ports) {
    const ok = await waitFor(`server on :${p}`, async () => (await statusOf(p)).running === true, 180_000);
    if (!ok) { shutdown(); return; }
  }
  console.log(paint('green', '\n=========================================================='));
  console.log(paint('green', ` READY  ->  open  http://localhost:${APP_PORT}`));
  console.log(paint('green', '=========================================================='));
  console.log(' 1. Sign in with Google (not the offline demo).');
  console.log(' 2. Tick the cameras to analyse -> header scope becomes "Selected" -> Activate Guard.');
  console.log(' 3. Watch the [status] line below. At the end:  node scripts/demo.mjs analysis-off --yes');
  try {
    const a = (await statusOf(APP_PORT)).anpr;
    if (a?.configured) console.log(` ANPR: ${a.healthy ? paint('green', 'healthy') + (a.device ? ', device ' + a.device : '') : paint('red', 'NOT healthy - ' + (a.error || 'unknown') + ' (plates fall back to Gemini)')}`);
    else console.log(' ANPR: off (plates read by Gemini, shown as "unverified read")');
  } catch { /* status shows it later */ }
  console.log(paint('dim', ' Ctrl+C stops everything.\n'));

  const beat = async () => {
    try {
      const s = await statusOf(APP_PORT);
      const ok = s.cameras.filter((c) => c.lastSuccessAt).length;
      const failing = s.cameras.filter((c) => c.failures > 0).length;
      console.log(`${paint('cyan', '[status]'.padEnd(10))} cameras ${s.cameras.length} (ok ${ok}, failing ${failing})  queue ${s.queue.queued} queued / ${s.queue.active} active  overdue ${s.overdue} (lag ${s.maxLagSeconds}s)  skipped-unchanged ${s.skippedUnchanged}`);
    } catch { /* server busy; next beat */ }
  };
  setInterval(beat, 30_000);
}

// ---------------------------------------------------------------- status
async function adminDb(cfg) {
  const { initializeApp, cert } = await import('firebase-admin/app');
  const { getFirestore } = await import('firebase-admin/firestore');
  return getFirestore(initializeApp({ credential: cert(JSON.parse(cfg.FIREBASE_SERVICE_ACCOUNT)) }));
}

async function status() {
  const cfg = loadConfig();
  const key = { 'X-Registry-Api-Key': cfg.REGISTRY_API_KEY };
  console.log(paint('cyan', '\nProcesses'));
  for (const port of [APP_PORT, APP_PORT + 1, APP_PORT + 2, APP_PORT + 3]) {
    try {
      const s = await getJson(`http://localhost:${port}/api/analysis/status`, key, 5000);
      const extra = s.role === 'worker' ? '' : `  cameras ${s.cameras.length} (ok ${s.cameras.filter((c) => c.lastSuccessAt).length}, failing ${s.cameras.filter((c) => c.failures > 0).length})  overdue ${s.overdue} (lag ${s.maxLagSeconds}s)  skipped-unchanged ${s.skippedUnchanged}`;
      console.log(`  ${PASS}  :${port}  ${String(s.role).padEnd(9)} queue=${s.backend}  ${s.queue.queued} queued / ${s.queue.active} active${extra}`);
      if (port === APP_PORT && s.anpr) console.log(`        ANPR: ${s.anpr.configured ? (s.anpr.healthy ? 'healthy' + (s.anpr.device ? ', ' + s.anpr.device : '') : paint('red', 'NOT healthy: ' + (s.anpr.error || '?'))) : 'off (Gemini reads plates)'}`);
      for (const c of s.cameras.filter((c) => c.failures > 0).slice(0, 5)) console.log(`        ${paint('yellow', c.name.slice(0, 28).padEnd(28))} failures ${c.failures}  ${String(c.lastError).slice(0, 60)}`);
    } catch (e) { if (port === APP_PORT) console.log(`  ${FAIL}  :${port}  not running (${e.message})`); }
  }
  try {
    const r = await fetch(`http://127.0.0.1:${MEDIA_PORT}/cam01/index.m3u8?cookieCheck=1`, { signal: AbortSignal.timeout(4000) });
    console.log(`  ${r.status === 401 ? PASS : WARN}  :${MEDIA_PORT}  media server (${r.status === 401 ? 'up' : 'HTTP ' + r.status})`);
  } catch { console.log(`  ${WARN}  :${MEDIA_PORT}  media server not running`); }

  console.log(paint('cyan', '\nFirestore'));
  try {
    const db = await adminDb(cfg);
    const flagged = await db.collection('cameras').where('serverAnalysis', '==', true).get();
    console.log(`  cameras flagged for server analysis: ${flagged.size}`);
    const since = Date.now() - 5 * 60_000;
    const logs = await db.collection('logs').orderBy('timestamp', 'desc').limit(300).get();
    const recent = logs.docs.map((d) => d.data()).filter((x) => x.timestamp.toDate().getTime() > since);
    const server = recent.filter((x) => x.analyzedBy === 'server');
    console.log(`  logs in the last 5 min: ${server.length} from the server, ${recent.length - server.length} from browsers`);
    if (server.length) console.log(`  newest server log: ${server[0].cameraName.slice(0, 28)} at ${server[0].timestamp.toDate().toLocaleTimeString()}`);
    else if (flagged.size) console.log(paint('yellow', '  cameras are flagged but no server logs yet - give it a minute, then check the worker window'));
  } catch (e) { console.log(`  ${FAIL}  could not read Firestore: ${String(e.message).slice(0, 80)}`); }
  console.log('');
  process.exit(0);
}

// ---------------------------------------------------------------- analysis-off
async function analysisOff() {
  const cfg = loadConfig();
  const db = await adminDb(cfg);
  const snap = await db.collection('cameras').where('serverAnalysis', '==', true).get();
  console.log(`${snap.size} camera(s) are flagged for server analysis.`);
  if (snap.size === 0) process.exit(0);
  if (!flag('--yes')) { console.log('Nothing changed. Run again with --yes to switch them all off.'); process.exit(0); }
  for (let i = 0; i < snap.docs.length; i += 400) {
    const batch = db.batch();
    snap.docs.slice(i, i + 400).forEach((d) => batch.update(d.ref, { serverAnalysis: false }));
    await batch.commit();
  }
  console.log('Done: server analysis is off for all cameras. (Activate Guard turns it on again for the ones you pick.)');
  process.exit(0);
}

// ---------------------------------------------------------------- stop
function stop({ quiet = false } = {}) {
  const ports = [...Array.from({ length: 10 }, (_, i) => APP_PORT + i), MEDIA_PORT, ...(flag('--anpr') ? [ANPR_PORT] : [])];
  const pids = new Set();
  if (WIN) {
    const out = spawnSync('netstat', ['-ano', '-p', 'tcp'], { encoding: 'utf8' }).stdout || '';
    for (const line of out.split(/\r?\n/)) {
      const m = line.match(/^\s*TCP\s+\S+:(\d+)\s+\S+\s+LISTENING\s+(\d+)/i);
      if (m && ports.includes(Number(m[1]))) pids.add(m[2]);
    }
  } else {
    for (const p of ports) { const o = spawnSync('lsof', ['-ti', `tcp:${p}`, '-sTCP:LISTEN'], { encoding: 'utf8' }).stdout || ''; o.split(/\s+/).filter(Boolean).forEach((x) => pids.add(x)); }
  }
  if (!pids.size) { if (!quiet) console.log('Nothing is listening on the demo ports (3000-3009, 8888).'); return 0; }
  for (const pid of pids) { killTree(pid); console.log(`stopped process ${pid}${quiet ? ' (previous run)' : ''}`); }
  return pids.size;
}

// ---------------------------------------------------------------- anpr-setup / anpr-test
function run(cmd, args, cwd) {
  console.log(paint('dim', '> ' + [cmd, ...args].join(' ')));
  const r = spawnSync(cmd, args, { cwd, stdio: 'inherit' });
  if (r.status !== 0) { console.log(`${FAIL}  command failed (exit ${r.status})`); process.exit(1); }
}

function anprSetup() {
  const py = findPython();
  if (!py) { console.log(`${FAIL}  Python 3 not found. Install Python 3.10-3.12 from python.org (tick "Add to PATH"), then run this again.`); process.exit(1); }
  console.log(`${INFO}  using ${py.cmd} ${py.version}`);
  if (!fs.existsSync(VENV_PY)) run(py.cmd, [...py.pre, '-m', 'venv', '.venv'], ANPR_DIR);
  run(VENV_PY, ['-m', 'pip', 'install', '--upgrade', 'pip'], ANPR_DIR);
  run(VENV_PY, ['-m', 'pip', 'install', '-r', flag('--gpu') ? 'requirements-gpu.txt' : 'requirements.txt'], ANPR_DIR);
  console.log(anprInstalled() ? `${PASS}  ANPR packages installed. Start it with:  node scripts/demo.mjs up --anpr` : `${FAIL}  installed, but the packages do not import - see the output above`);
  process.exit(anprInstalled() ? 0 : 1);
}

/** Runs scripts/check-anpr.mjs against the configured service, on a real frame from the camera grid. */
function anprTest() {
  const cfg = loadConfig();
  if (!cfg.ANPR_SERVICE_URL) cfg.ANPR_SERVICE_URL = `http://127.0.0.1:${ANPR_PORT}`;
  let frame = argv.find((a, i) => !a.startsWith('--') && a !== 'anpr-test' && !(i > 0 && argv[i - 1].startsWith('--')));
  if (!frame) {
    frame = path.join(ROOT, '.demo-logs', 'anpr-frame.jpg');
    fs.mkdirSync(path.dirname(frame), { recursive: true });
    const enc = (v) => encodeURIComponent(v).replace(/@/g, '%40');
    const cam = opt('--cam', 'cam05');
    console.log(`${INFO}  grabbing a frame from ${cam} ...`);
    const g = spawnSync('ffmpeg', ['-y', '-loglevel', 'error', '-rtsp_transport', 'tcp', '-i', `rtsp://${enc(cfg.GRID_EMAIL)}:${enc(cfg.GRID_PASSWORD)}@${GRID_HOST}:8554/stream/${cam}`, '-vframes', '1', frame], { timeout: 30_000 });
    if (g.status !== 0 || !fs.existsSync(frame)) { console.log(`${FAIL}  could not grab a frame (grid down?). Pass your own image:  node scripts/demo.mjs anpr-test path/to/frame.jpg`); process.exit(1); }
  }
  const r = spawnSync(process.execPath, [path.join(ROOT, 'scripts', 'check-anpr.mjs'), frame, '--cameras', opt('--cameras', '50'), '--interval', opt('--interval', '60')], { stdio: 'inherit', env: cfg });
  process.exit(r.status ?? 1);
}

// ---------------------------------------------------------------- main
process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
switch (command) {
  case 'check': process.exit(await check(loadConfig()) ? 1 : 0); break;
  case 'up': await up(); break;
  case 'status': await status(); break;
  case 'analysis-off': await analysisOff(); break;
  case 'stop': stop(); break;
  case 'anpr-setup': anprSetup(); break;
  case 'anpr-test': anprTest(); break;
  default:
    console.log(fs.readFileSync(fileURLToPath(import.meta.url), 'utf8').split('*/')[0].replace(/^#!.*\r?\n/, '').replace(/^\/\*\*?|^ \* ?/gm, ''));
}
