export interface GlossaryTerm {
  term: string;
  definition: string;
  category: 'Camera Setup' | 'Detection' | 'Alerts & Security' | 'Data & Export' | 'Registry & GIS';
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  { term: 'Camera', category: 'Camera Setup', definition: 'A single registered camera in OmniSee — a webcam, a remote RTSP/IP feed, or a simulated feed. Each camera has its own thresholds, rules, and connection settings.' },
  { term: 'Feed Source', category: 'Camera Setup', definition: 'Where a camera\'s video comes from: your device\'s camera, a Remote Link (RTSP/ONVIF/WHEP/HLS URL), or a built-in Simulated Feed for testing without hardware.' },
  { term: 'RTSP / ONVIF', category: 'Camera Setup', definition: 'Standard protocols most IP cameras and DVRs speak. RTSP streams video; ONVIF is a discovery/config standard many vendors support. Browsers can\'t play RTSP directly, so a bridge (like go2rtc) is usually required.' },
  { term: 'Remote Link Feed', category: 'Camera Setup', definition: 'A camera configured to pull video from an external URL instead of a local device — typically a bridge exposing RTSP as WebRTC, HLS, or an MJPEG snapshot stream.' },
  { term: 'Simulated Feed', category: 'Camera Setup', definition: 'A synthetic, animated CCTV-style feed used to test and demo OmniSee without any physical camera. Turns on automatically if no camera hardware is available.' },
  { term: 'Sensitivity', category: 'Detection', definition: 'A 1–10 dial per camera controlling how readily the AI flags an event as unusual. Higher sensitivity means more borderline activity gets escalated to an alert.' },
  { term: 'People / Vehicle Threshold', category: 'Detection', definition: 'The count of people or vehicles in a single frame above which OmniSee treats the scene as noteworthy for that camera.' },
  { term: 'Suspicious Rules', category: 'Detection', definition: 'Free-text, camera-specific instructions (e.g. "a white van in the driveway") the AI uses alongside thresholds to decide what counts as an anomaly for that particular camera.' },
  { term: 'Sync Frequency', category: 'Detection', definition: 'How often, in seconds, a camera captures a frame and sends it for analysis. Lower values mean faster detection but more analysis calls.' },
  { term: 'Known Faces', category: 'Detection', definition: 'Reference photos of people you want identified by name instead of being reported as an unknown person. Compared against each analyzed frame.' },
  { term: 'Watchlist', category: 'Alerts & Security', definition: 'A list of vehicle plates flagged for tracking. Any plate the AI reads off a frame is checked against this list, and a match raises a high-priority alert.' },
  { term: 'Watchlist Hit', category: 'Alerts & Security', definition: 'A log entry where a detected plate matched an entry on the Watchlist — shown with its own badge, distinct from a general "Suspicious" flag.' },
  { term: 'Alert', category: 'Alerts & Security', definition: 'A specific warning generated by the AI for one analysis cycle — e.g. an unknown person, a threshold breach, or a matched suspicious rule.' },
  { term: 'Webhook', category: 'Alerts & Security', definition: 'A URL you provide that OmniSee POSTs event data to automatically, so alerts can reach another system (e.g. your own alerting pipeline) in real time.' },
  { term: 'Offline Mode', category: 'Data & Export', definition: 'Shown when the app can\'t reach the cloud database. Your settings and cameras keep working from a local backup and re-sync automatically once the connection returns.' },
  { term: 'Route History', category: 'Data & Export', definition: 'The chronological sequence of camera sightings for a searched plate, plotted as a path on the Registry map — built by joining each sighting\'s camera location in time order.' },
  { term: 'Registry', category: 'Registry & GIS', definition: 'The single source of truth for every camera you manage — one record per camera, covering location, department, ownership, type, connectivity, and storage, independent of the live Feed view.' },
  { term: 'Department', category: 'Registry & GIS', definition: 'The organizational owner assigned to a camera, used to group and filter cameras in the Registry and on the map.' },
  { term: 'Ownership', category: 'Registry & GIS', definition: 'Who owns or operates the physical camera — e.g. a specific municipal body, contractor, or institution — distinct from the department using it.' },
  { term: 'Camera Type', category: 'Registry & GIS', definition: 'The physical form factor of the device: fixed, PTZ (pan-tilt-zoom), dome, bullet, or other — recorded for planning and vendor management.' },
  { term: 'Connectivity Status', category: 'Registry & GIS', definition: 'Whether a camera is declared online, offline, degraded, or unknown in the registry record — set manually or via bulk import, and independent of whether it is actually streaming right now (see Live Status). Drives the pin color on the Registry map.' },
  { term: 'Live Status', category: 'Registry & GIS', definition: 'Whether a camera\'s feed is actually connected right now — connecting, live, or error — measured in real time on the Feed tab. Distinct from Connectivity Status, which is a manually-set registry field and can be stale.' },
  { term: 'Maintenance Status', category: 'Registry & GIS', definition: 'Whether a camera is operational, needs maintenance, or has been decommissioned — tracked independently of live connectivity.' },
  { term: 'Coverage Layer', category: 'Registry & GIS', definition: 'The faint radius drawn around each camera pin on the map, giving a rough visual sense of monitored area and where coverage gaps exist.' },
  { term: 'Bulk Import', category: 'Registry & GIS', definition: 'Onboarding many cameras at once from a CSV file, instead of adding them one at a time. Available to Admin accounts in the Registry tab.' },
  { term: 'Registry API', category: 'Registry & GIS', definition: 'A server-to-server REST API (documented in docs/registry-api.md) that lets external systems onboard, update, or remove cameras without using the app UI.' },
  { term: 'Gap Analysis Report', category: 'Registry & GIS', definition: 'An on-demand report in the Registry tab surfacing unlocated cameras, offline/degraded cameras, ageing infrastructure, and stale (un-analyzed) cameras.' },
  { term: 'Audit Trail', category: 'Registry & GIS', definition: 'An append-only log of every camera created, updated, or deleted in the registry — who did it, how (manual, bulk import, or API), and when. Visible to Admin accounts.' },
  { term: 'Role (Operator / Admin)', category: 'Registry & GIS', definition: 'Operators can view and search the registry; Admins can additionally bulk-import, delete cameras, manage the watchlist, and view the audit trail.' },
];

export interface OperatingStep {
  step: number;
  title: string;
  description: string;
  tab: 'Feed' | 'Logs' | 'Settings' | 'Registry' | 'Account';
}

export const OPERATING_STEPS: OperatingStep[] = [
  { step: 1, title: 'Sign in', description: 'Use Google Sign-In, or choose "Bypass Login" to try OmniSee in an offline guest demo that saves to your browser only.', tab: 'Account' },
  { step: 2, title: 'Add a camera', description: 'In Settings, click "Add Camera" to register a new camera, or onboard many at once with a CSV in Registry. Give each a friendly name so it\'s easy to pick out later.', tab: 'Settings' },
  { step: 3, title: 'Choose a feed source', description: 'Point the camera at your device camera, paste a Remote Link URL for an RTSP/IP camera, or switch on the Simulated Feed to try it without hardware.', tab: 'Settings' },
  { step: 4, title: 'Set thresholds and rules', description: 'Tune Sensitivity, People/Vehicle thresholds, and write any Suspicious Rules specific to that camera\'s view.', tab: 'Settings' },
  { step: 5, title: 'Complete the registry record', description: 'Fill in department, ownership, camera type, coordinates, and storage details so the camera is correctly placed and reportable in Registry.', tab: 'Settings' },
  { step: 6, title: 'Activate Guard', description: 'Press "Activate Guard" in the header to start the analysis loop. Watch the live feed and Alert Center for results.', tab: 'Feed' },
  { step: 7, title: 'Review activity and search a plate', description: 'Use Logs to browse the archive, export a CSV, or search a specific vehicle plate and view its route on the Registry map.', tab: 'Logs' },
  { step: 8, title: 'Check the registry health', description: 'Filter and search the fleet in Registry, run the gap-analysis report, and review the audit trail (Admin) for recent changes.', tab: 'Registry' },
  { step: 9, title: 'Manage known faces and the watchlist', description: 'Upload reference photos so people are identified by name, and add plates you want flagged on sight.', tab: 'Settings' },
];
